name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel twine build

      - name: Build
        run: |
          python -m build --sdist --wheel .
          SDIST_PATH=$(ls dist/*.tar.gz)
          WHEEL_PATH=$(ls dist/*.whl)
          echo "SDIST_PATH=${SDIST_PATH}" >> $GITHUB_ENV
          echo "WHEEL_PATH=${WHEEL_PATH}" >> $GITHUB_ENV

      - name: Release
        uses: crazy-max/ghaction-github-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: True
          fail_on_unmatched_files: True
          files: |
            ${{ env.SDIST_PATH}}
            ${{ env.WHEEL_PATH}}
